add_newline = false
command_timeout = 1000

format = """
$username@$hostname $directory $git_branch $git_status $golang $nodejs $python $kubernetes $time
$character
"""

[directory]
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "bold #89b4fa"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"

[golang]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[kubernetes]
symbol = "⎈ "

[time]
disabled = false
time_format = "%H:%M:%S"
format = " [$time]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
