tap "hashicorp/tap", trusted: true
tap "systemmanic/aws-session-manager-plugin", "https://github.com/Systemmanic/homebrew-aws-session-manager-plugin.git", trusted: true
# Universal Command-Line Interface for Alibaba Cloud
brew "aliyun-cli"
# Automate deployment, configuration, and upgrading
brew "ansible"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Official Amazon AWS command-line interface
brew "awscli"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Dependency Manager for PHP
brew "composer"
# GNU compiler collection
brew "gcc"
# Task is a task runner/build tool that aims to be simpler and easier to use
brew "go-task"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Much more powerful alternative to kubectx and kubens
brew "kubie"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# CLI proxy to minimize LLM token consumption
brew "rtk"
# Graphical command-line client for SSH
brew "sshs"
# Linter for Terraform files
brew "tflint"
# Creates fully functional virtual k8s cluster inside host k8s cluster's namespace
brew "vcluster"
# Terraform
brew "hashicorp/tap/terraform"
# Vault
brew "hashicorp/tap/vault", trusted: true
go "cmd/go"
go "cmd/gofmt"
go "github.com/golangci/golangci-lint/v2/cmd/golangci-lint"
go "golang.org/x/tools/gopls"
go "github.com/goreleaser/goreleaser/v2"
winget "CPUID HWMonitor 1.61", id: "CPUID.HWMonitor"
winget "DBeaver 26.1.3 (current user)", id: "DBeaver.DBeaver.Community"
winget "Docker Desktop", id: "Docker.DockerDesktop"
winget "Git", id: "Git.Git"
winget "Google Drive", id: "Google.GoogleDrive"
winget "Internet Download Manager", id: "Tonec.InternetDownloadManager"
winget "Logitech G HUB", id: "Logitech.GHUB"
winget "Microsoft Teams", id: "Microsoft.Teams"
winget "Microsoft Visual Studio Code (User)", id: "Microsoft.VisualStudioCode"
winget "Obsidian", id: "Obsidian.Obsidian"
winget "OpenVPN Connect", id: "OpenVPNTechnologies.OpenVPNConnect"
winget "PowerToys (Preview) x64", id: "Microsoft.PowerToys"
winget "Redis Insight 3.6.0", id: "RedisInsight.RedisInsight"
winget "RivaTuner Statistics Server 7.3.7", id: "Guru3D.RTSS"
winget "Slack", id: "SlackTechnologies.Slack"
winget "Steam", id: "Valve.Steam"
winget "SteelSeries GG 116.0.0", id: "SteelSeries.GG"
winget "Windows Terminal", id: "Microsoft.WindowsTerminal"
winget "WinRAR 7.13 (64-bit)", id: "RARLab.WinRAR"
winget "Zoom Workplace", id: "Zoom.Zoom.EXE"
winget "Docker Desktop", id: "XP8CBJ40XLBWKX", source: "msstore"
winget "Microsoft Visual Studio Code (User)", id: "XP9KHM4BK9FZ7Q", source: "msstore"
winget "PowerToys (Preview) x64", id: "XP89DCGQ3K6VLD", source: "msstore"
npm "@continuedev/cli"
npm "@mermaid-js/mermaid-cli"
npm "ccstatusline"
npm "corepack"
npm "omniroute"
