##### ===== GENERAL ===== #####

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Ensure tmux uses your shell env
set -g default-command "${SHELL}"

set -g mouse on
set -g focus-events on

# Prefix remap
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Faster escape
set -s escape-time 0

# Better indexing
set -g base-index 1
setw -g pane-base-index 1

# Renumber window when any of them is closed
set -g renumber-windows on

##### ===== WINDOWS & PANES ===== #####

# Keep working directory

# Open new windows in the current directory
bind c new-window -c "#{pane_current_path}"

# Open splits in the current directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

##### ===== NAVIGATION (VIM STYLE) ===== #####

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### ===== RESIZE ===== #####

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### ===== UTILITIES ===== #####

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Clear screen
bind C-l send-keys 'C-l'

##### ===== COPY MODE ===== #####

setw -g mode-keys vi

# Start selection
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Copy selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# tmux sessionizer
bind-key -n C-f display-popup -E "tms switch"

##### ===== STATUS BAR ===== #####

# ── Basics
set -g status on
set -g status-interval 5

# ── Colors
set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"

# ── Left
set -g status-left "#[fg=#89b4fa,bold] #S "

# ── Windows
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"

set -g window-status-format "#[fg=#6c7086] #I #{b:pane_current_path} "
set -g window-status-current-format "#[fg=#a6e3a1,bold] #I #{b:pane_current_path} "

# ── Right
set -g status-right "#(top -bn1 | grep 'Cpu' | awk '{print \"CPU \" $2}') #[fg=#6c7086]| #[fg=#fab387]#(free -h | awk '/Mem/ {print \"RAM \" $3}') #[fg=#6c7086]| #[fg=#a6adc8]%H:%M"

##### ===== PERFORMANCE ===== #####

# Increase scrollback
set -g history-limit 10000

set -g status-interval 5

##### ===== PLUGINS (NIX-MANAGED) ===== #####

# resurrect
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# yank (clipboard)
set -g @yank_selection 'clipboard'
